spring:
  config:
    import: file:properties/@properties.file@.properties
  profiles:
    active: ${TEST_ENV}
    default: tst

logging:
  config: classpath:logback-spring.xml
  level:
    mb.testframeworks: info

mb-testframeworks-java:
  is-ci: ${IS_CI}
  webdriver:
    chromeVersion: ${CHROME_VERSION}

  services:
    petstore-v3:
      base-url: https://petstore3.swagger.io/api/v3
    petstore-analyzer-v1:
      base-url: http://localhost:8080
